### ISSUE TITLE
Looking forward to the codes.

### ISSUE THREAD

**Issue by Harry-Zhi** [NVlabs/SCOPS#1]
Very great work!
Is there an expected release date?

**Comment by XavierCHEN34** [comment]
me too

**Comment by varunjampani** [comment]
Just got the permissions. We will be adding the code very soon.

**Comment by Harry-Zhi** [comment]
> Just got the permissions. We will be adding the code very soon.

Thank you Varun for releasing the code. 
Two extra questions if you do not mind, 
1. Will scripts about PASCAL dataset and training  be released?
2. Saliency detection part. Is saliency map generated for each train/test image before training, which is not included here?

**Comment by hfslyc** [comment]
> > Just got the permissions. We will be adding the code very soon.
> 
> Thank you Wayne @hfslyc and Varun @varunjampani for releasing the code.
> Two extra questions if you do not mind,
> 
> 1. Will scripts about PASCAL dataset and training  be released?
Yes, it will be released.
> 2. Saliency detection part. Is saliency map generated for each PASCAL train and test images before training?
Yes, it's generated before train/test phase.

**Comment by Harry-Zhi** [comment]
> > > Just got the permissions. We will be adding the code very soon.
> > 
> > 
> > Thank you Wayne @hfslyc and Varun @varunjampani for releasing the code.
> > Two extra questions if you do not mind,
> > 
> > 1. Will scripts about PASCAL dataset and training  be released?
> 
> Yes, it will be released.
> 
> > 1. Saliency detection part. Is saliency map generated for each PASCAL train and test images before training?
> 
> Yes, it's generated before train/test phase.

Great. Thanks!
