### ISSUE TITLE
Module  Not  Found  Error

### ISSUE THREAD

**Issue by Elaineok** [NVlabs/SCOPS#13]
Hello, I run this program.In  ./tps/rand_tps.py. "from tps_stn_pytorch.tps_grid_gen  import  TPSGridGen" is error.
**No module named 'tps_stn_pytorch'.**

**How can I find 'tps_stn_pytorch' module?**

**Comment by XinWangg** [comment]
Hello!  :)
Have you solved it?

**Comment by Elaineok** [comment]
yes， problem was solved

XinWangg <notifications@github.com> 于2020年8月16日周日 下午7:18写道：

**Comment by jonwomack** [comment]
If you run into this error, cloning https://github.com/WarBean/tps_stn_pytorch should fix it.
